name: Pytest_conduit_3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  index3:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test_proj/requirements.txt ]; then pip install -r test_proj/requirements.txt; fi

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable

    - name: Builds and Starts
      run: |
          docker-compose up -d

    - name: Sleep for 70 seconds
      run: sleep 70s
      shell: bash

    - name: Test with pytest
      run: |
        pytest test_proj/test_index_3.py

    - name: Collect docker logs
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'

    - name: Archive execution artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-logs
        path: ./logs

